name: Scheduled Scraper Job

on:
  # Run 3 times daily at UTC 06:00, 09:00, 13:00
  schedule:
    - cron: '0 6,9,13 * * *'
  
  # Allow manual trigger for testing
  workflow_dispatch:
  
jobs:
  scrape:
    runs-on: ubuntu-latest  # Changed to ubuntu for better database compatibility

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scraper/requirements.txt

    - name: Run parser and save to database
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: python scraper/scraper.py
